### PR TITLE
Lln function

### PR DESCRIPTION
**Pull request by jackbunge1**
* updating create_plots.R to create a function, lllustrate_lln, which creates scatterplots of the number of rolls (x-axis) by the current mean (y-axis). 
* updates the latex code and paper to include new figures (scatterplots) and a brief overview of them.

### CODE REVIEW

**Comment by jackbunge1** [comment]
I forgot to add the issue number to the commits, so it's a different issue than the practice task; ill take a look at this tomorrow

**Comment by SimonFreyaldenhoven** [comment]
That's ok! Adding the issue number is just helpful for discussing changes inside the issue, but other than that, it does not make a difference. So don't worry about it!

**Review by SimonFreyaldenhoven — COMMENTED** [review]
@jackbunge1 Looks great! I just have one small comment in the code above.

Can you add the log file and pdf a well so I can see those?

**Comment by jackbunge1** [comment]
ok, thanks for reviewing simon. I changed the path and have also uploaded the log and pdf (and time_log just in case). let me know if there are any other changes, thanks

**Comment by SimonFreyaldenhoven** [comment]
Thanks! I noticed a few references in the not appear broken/wrong - can you take a look?

image

and let's talk about your question in person later -I want to make sure I understand it correctly.

**Comment by jackbunge1** [comment]
yeah, I'll take a look at it. And sounds good, re the question, thanks

**Comment by jackbunge1** [comment]
just finished updating the paper, should hopefully look normal now. also, I'm meeting with IT tomorrow about the stata issue, hoping to have it resolved then.

**Review by SimonFreyaldenhoven — APPROVED** [review]
@jackbunge1 Thanks! looks great!

**Pull request merged**
